### ISSUE TITLE
Additional clang-tidy argument support (e.g, -p)

### ISSUE THREAD

**Issue by KazNX** [alesiong/clang-tidy-linter#4]
Hi,

The "clangTidy.xxx" settings do not provide adequate support for configuring clang-tidy for a workspace. In particular, I need support for clang-tidy "-p" option to point it at the "compile_commands.json" file generated by CMake. More broadly speaking, there should be settings to control additional arguments passed to clang-tidy; akin to "clangTidy.extraCompilerArgs", but for clang-tidy, not the compiler.

This boils down to the following command line:
`clang-tidy -p <cmake-buid-directory> <target-source-file>`

Thanks.

**Comment by KazNX** [comment]
I've created a pull request which supports passing any clang-tidy argument. It also cleans up replacements to effect all associated replacements on one click.

[pull-request-6](https://github.com/alesiong/clang-tidy-linter/pull/6)

**Comment by EugeneZelenko** [comment]
It'll be great if CLang-tidy plugin will get compile database location from CMake plugin (== CMake output).

**Comment by SoftwareApe** [comment]
@EugeneZelenko It would be good if that is optional though (not all projects are CMake based).

**Comment by EugeneZelenko** [comment]
Sure, this should be optional parameter.

**Comment by DragonAxe** [comment]
Now that [pull-request-6](https://github.com/alesiong/clang-tidy-linter/pull/6) has been merged, does the `-p` flag work? If so, am I using the `extraCompilerArgs` correctly? I've tried all of these:
```
"clangTidy.extraCompilerArgs": [
        "-Weverything",
        "-p",
        "${workspaceFolder}/../BuildArea/cmake/AllProjects/Release/"
      ]
```
```
"clangTidy.extraCompilerArgs": [
        "-Weverything",
        "-p ${workspaceFolder}/../BuildArea/cmake/AllProjects/Release/"
      ]
```
```
"clangTidy.extraCompilerArgs": [
        "-Weverything",
        "-p=${workspaceFolder}/../BuildArea/cmake/AllProjects/Release/"
      ]
```
I get an error squiggly at the top of my source files similar to this:
```
unknown argument: '-p=${workspaceFolder}/../BuildArea/cmake/AllProjects/Release/' (clang-diagnostic-error)Clang Tidy([])
```
Edit:
Ah, it doesn't appear that this extension has been released since the pull request was merged (on Dec 18, 2018):

Version | 0.0.2 |  
-- | -- | --
Released on | 6/13/2018, 12:19:36 AM |  
Last updated | 6/16/2018, 10:05:34 PM |  
Publisher | alesiong |  
Unique Identifier | alesiong.clang-tidy-linter |

**Comment by kenkit** [comment]
I use it like this 
```json
  "clangTidy.extraCompilerArgs":["-p","build\\compile_commands.json"],
```
Agreed it doesn't work

**Comment by KazNX** [comment]
It's been a while since I looked at this, but try using:
```json
  "clangTidy.args": [ "-p", "build/compile_commands.json" ]
```

The `clangTidy.extraCompilerArgs` option was there before pull request 6 and is passed to the clang-tidy command line option `--extra-arg`, which won't work. The changelist added `clangTidy.args` which are passed as is to the clang-tidy command line.

**Comment by kenkit** [comment]
If only the devs on the project fixed this project.
I'm currently using https://github.com/alesiong/clang-tidy-linter/pull/22

**Comment by KazNX** [comment]
VSCode now has native clang-tidy support.
